id: P004423
initial_creation_type: ocr
source_metadata:
  id: bdr:W3MS52
  title: དགྲ་ལྷའི་བསངས་ཆོག་དང་མཆོད་སྦྱིན་བསང་གི་ཆོ་ག
  author: ''
  volumes:
    635d21f4e6ac4e8aa52f672b06ae399c:
      image_group_id: I3MS54
      title: ''
      volume_number: 1
      total_pages: 244
      base_file: v001.txt
